include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_relative_imports: true
    curly_braces_in_flow_control_structures: true
    lines_longer_than_80_chars: true
    unnecessary_lambdas: true