name: shopping_list
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^5.0.5
  get_it: ^7.2.0

  # Features
  list_books:
    path: ../../features/list_books

  # Services
  design_system:
    path: ../../services/design_system

  network:
    path: ../../services/network

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
